### ISSUE TITLE
希望新增多地址更新tracker链接

### ISSUE THREAD

**Issue by qgdyyg** [ifloppy/Naria#1]
https://gitea.com/XIU2/TrackersListCollection/raw/branch/master/all.txt
https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt
https://cdn.jsdelivr.net/gh/DeSireFire/animeTrackerList/AT_all.txt

**Comment by ifloppy** [comment]
感谢您的支持。我的仓库会有人注意到，这是我没有想到的。我正在开始完成这个功能，在完成后我将会关闭这个Issue。
